In [1]:
# @title Câu 1
import numpy as np                  # Import Numpy
import tensorflow as tf             # Import TensorFlow
import torch

print(np.zeros((3,4)))
print(tf.zeros((3,4)))
print(torch.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(3, 4), dtype=float32)
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [10]:
# @title Câu 2
print(np.ones((3,4)))
print(tf.ones((3,4)))
print(torch.ones((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [11]:
# @title Câu 3
print(np.full((3,4),5))
print(tf.fill((3,4),5))
print(torch.full((3,4),5))

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)
tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]])
