In [ ]:
import numpy as np

arr_1 = np.array([[1,2],[3,4]])

# chuyển vị array
# Cách 1: Sử dụng hàm np.transpose()
arr_transposed_1 = np.transpose(arr_1)


# Cách 2 : Sử dụng toán tử T
arr_transposed_2 = arr_1.T

# In  ra màn hình 
print("array 1: \n",arr_1)
print("array 1 sau khi chuyển vị, cách 1: \n",arr_transposed_1)
print("array 1 sau khi chuyển vị, cách 2: \n",arr_transposed_2)

In [6]:
import torch

# Tạo tensor 2d
tensor_1 = torch.tensor([[1,2],
                         [3,4]])

# torch.transpose(input,dim0,dim1) với:
# dim0,dim1:các chiều được chọn để chuyển vị 
tensor_transposed_1 = torch.transpose(tensor_1,0,1)

tensor_transposed_2 = torch.t(tensor_1)

print("tensor 1: \n",arr_1)
print("tensor 1 sau khi chuyển vị, cách 1: \n",arr_transposed_1)
print("tensor 1 sau khi chuyển vị, cách 2: \n",arr_transposed_2)

array 1: 
 [[1 2]
 [3 4]]
array 1 sau khi chuyển vị, cách 1: 
 tensor([[1, 3],
        [2, 4]])
array 1 sau khi chuyển vị, cách 2: 
 tensor([[1, 3],
        [2, 4]])


In [8]:
import tensorflow as tf

tensor_1 = tf.constant([[1,2],
                        [3,4]])

#chuyển vị tensor
tensor_transposed = tf.transpose(tensor_1)
print("tensor 1: \n",tensor_1)
print("tensor 1 sau khi chuyển vị: \n",tensor_transposed)

tensor 1: 
 tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tensor 1 sau khi chuyển vị: 
 tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)
