In [1]:
# @title Câu 1
import numpy as np                  # Import Numpy
import tensorflow as tf             # Import TensorFlow
import torch

lst_data = [1,2,3]

print(np.array(lst_data))
print(torch.tensor(lst_data))
print(tf.constant(lst_data))


[1 2 3]
tensor([1, 2, 3])
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [2]:
# @title Câu 2
lst_data_matrix = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

tensor = np.array(lst_data_matrix)
print("Hình dạng của mảng: ",tensor.shape)  # In ra shape của tensor
print("Kiểu dữ liệu của mảng: ",tensor.dtype)  # In ra kiểu dữ liệu của tensor
print("Loại của mảng: ",type(tensor)) # In ra loại tensor
print("Mảng \n",tensor)
print("\n")
tensor = torch.tensor(lst_data_matrix, dtype=torch.float32)
print("Hình dạng của mảng: ",tensor.shape)  # In ra shape của tensor
print("Kiểu dữ liệu của mảng: ",tensor.dtype)  # In ra kiểu dữ liệu của tensor
print("Loại của mảng: ",type(tensor)) # In ra loại tensor
print("Thiết bị lưu trữ tensor :", tensor.device) # In ra thiết bị lưu trữ tensor
print("\n")
tensor = tf.constant(lst_data_matrix, dtype=tf.float32)
print("Hình dạng của mảng: ",tensor.shape)  # In ra shape của tensor
print("Kiểu dữ liệu của mảng: ",tensor.dtype)  # In ra kiểu dữ liệu của tensor
print("Loại của mảng: ",type(tensor)) # In ra loại tensor
print("Thiết bị lưu trữ tensor :", tensor.device) # In ra thiết bị lưu trữ tensor

Hình dạng của mảng:  (3, 3)
Kiểu dữ liệu của mảng:  int32
Loại của mảng:  <class 'numpy.ndarray'>
Mảng 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Hình dạng của mảng:  torch.Size([3, 3])
Kiểu dữ liệu của mảng:  torch.float32
Loại của mảng:  <class 'torch.Tensor'>
Thiết bị lưu trữ tensor : cpu


Hình dạng của mảng:  (3, 3)
Kiểu dữ liệu của mảng:  <dtype: 'float32'>
Loại của mảng:  <class 'tensorflow.python.framework.ops.EagerTensor'>
Thiết bị lưu trữ tensor : /job:localhost/replica:0/task:0/device:CPU:0
